name: Issues

on:
  issues:
    types: [opened]
    
jobs:
  check-issue:
     name: Check issue
     runs-on: ubuntu-22.04
     steps:
       - name: Check issue title
         run: |
           title="${{ github.event.issue.title }}"
           if [[ $title =~ [A-Z] ]]; then
           echo "PR title starts with an uppercase letter"
           exit 0
           else
           echo "PR title did not start with an uppercase letter"
           exit 1
           fi
