name: Test

on:
  push:
    branches:
    - 'main'

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Echo Stuff
        run: |
          echo "Hello"
