name: Test

on:
  push:
    branches:
    - 'main'

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
      - name: Unit Tests
        run: go test
      
