name: Test

on:
  push:
    branches:
    - 'main'

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          fetch-depth: 0
      - name: Echo Stuff
        run: |
          echo "Hello"
