name: Test

on:
  push:
    branches:
    - 'main'

jobs:
  lint:
     name: Lint
     runs-on: ubuntu-22.04
     steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Unit Tests
        run: go test
